### ISSUE TITLE
project scope

### ISSUE THREAD

**Issue by codejanovic** [casid/jusecase-builders#1]
as stated in the projects description
> Builders for descriptive unit test setups.

i am not sure if this project should really be limited to testing purposes only. i think that many builders, especially some convenience builders for collection types, are very useful even outside test scope.

**Usecases**
so for example, considering these three daily usecases:

``` 
final List<String> list = new ArrayList<>();
final List<String> list2 = new ArrayList<>();

final List<String> unmodifiable = Collections.unmodifiableList(list);
final List<String> unmodifiableCopy = Collections.unmodifiableList(new ArrayList<>(list));
final List<String> aggregate = new ArrayList<>(list);
aggregate.addAll(list2);
final List<String> unmodifiableAggregate = Collections.unmodifiableList(aggregate);
```

it could be also very useful to use the provided builders within production code:
```
final List<String> list = new ArrayList<>();
final List<String> list2 = new ArrayList<>();

final List<String> unmodifiable = an(unmodifiable(list));
final List<String> unmodifiableCopy = an(unmodifiable(copy(of(list))));
final List<String> unmodifiableAggregate = an(unmodifiable(aggregate(of(list, list2))));
```
the same goes for every other collection type. 

What do you think about it?

**Comment by casid** [comment]
Sounds very good to me!

Looking forward to your pull request :-)

And I especially like the sound of an(), would love to see that feature added, too.
